config/routes.rb
Rails.application.routes.draw do
  # get '/students', to: 'students#index', as: 'students'
  # get '/students/new', to: 'students#new', as: 'new_student'
  # post '/students', to: 'students#create'
  # get '/developers', to: 'students#index', as: 'students'
  resources :students, only: [:index, :new, :create]
  # resources :dogs, only: [:index, :new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
  end

  def create
    student = Student.create(name: params[:name])
    redirect_to students_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # def make_link_to(body, path)
  #   "<a href='#{path}'>#{body}</a>".html_safe
  # end

  # def text_field_tag(field_name)
  #   "<input type='text' name='#{field_name.to_s}' id='#{field_name.to_s}'/>".html_safe
  # end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>All Students</h1>

<% @students.each do |student| %>
  <%= student.name %>
<% end %>

<%= link_to "Create a Student", new_student_path %>

<a href='<%= new_student_path%>' >Create a Student</a>

app/views/students/new.html.erb
<h1>Create a Student</h1>

<%= form_tag(students_path) do %>
  <%= text_field_tag :name %>
  <%= submit_tag "Make a Student"%>
<% end %>

<%= link_to "Back", students_path %>